proyecto libros

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -12,6 +12,20 @@ jobs:
 
       - name: Descargar código
         uses: actions/checkout@v4
+      - name: Comprobar secrets
+        run: |
+          if [ -z "${{ secrets.DOCKERHUB_USER }}" ]; then
+            echo "ERROR: DOCKERHUB_USER está vacío"
+            exit 1
+          fi
+
+          if [ -z "${{ secrets.DOCKERHUB_PASS }}" ]; then
+            echo "ERROR: DOCKERHUB_PASS está vacío"
+            exit 1
+          fi
+
+          echo "DOCKER_USERNAME está configurado"
+          echo "DOCKER_PASSWORD está configurado"
       - name: Iniciar sesión en Docker Hub
         uses: docker/login-action@v3
         with:
